Repository JabRef/JabRef-Word-Addin, pull requests merged in 2021-06, with the labels that each got.

#31 Log in page
  .eslintrc.json
  assets/icon-128.png
  assets/icon-16.png
  assets/icon-32.png
  assets/icon-80.png
  assets/jabref-icon-128.svg
  assets/jabref-icon-16.svg
  assets/jabref-icon-32.svg
  assets/jabref-icon-80.svg
  assets/logo-filled.png
  codegen.yml
  manifest.xml
  package.json
  src/Utils/ProtectedRoutes.tsx
  src/Utils/apolloClient.ts
  src/graphql/mutation/login.graphql
  src/graphql/mutation/logout.graphql
  src/graphql/query/me.graphql
  src/taskpane/components/App.tsx
  src/taskpane/components/Header.tsx
  src/taskpane/components/HeroList.tsx
  src/taskpane/components/InputField.tsx
  src/taskpane/components/Layout.tsx
  src/taskpane/components/Progress.tsx
  src/taskpane/components/Wrapper.tsx
  src/taskpane/index.tsx
  src/taskpane/pages/dashboard.tsx
  src/taskpane/pages/login.tsx
  src/taskpane/taskpane.css
  src/taskpane/taskpane.html
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: status: needs changes, status: ready-for-review

#32 Add dotenv
  .eslintrc.json
  package.json
  src/Utils/apolloClient.ts
  webpack.config.js
  yarn.lock
Labels: status: needs changes

#66 Run dependabot only monthly
  .github/dependabot.yml
Labels: status: ready-for-review

#64 Fix office word debug start
  .vscode/tasks.json
  package.json
  yarn.lock
Labels: status: ready-for-review
